services:
  - type: pserv
    name: hmis-postgres
    env: postgres
    startCommand: postgres
    plan: free

  - type: web
    name: hmis-backend
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && flask db upgrade && python seed.py && gunicorn -w 4 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: DATABASE_URL
        fromService:
          name: hmis-postgres
          type: pserv
          property: externalDatabaseUrl
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://hmis-frontend.onrender.com

  - type: web
    name: hmis-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://hmis-backend.onrender.com
